# Generated by Django 4.2.9 on 2024-02-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probe_agile_data', '0007_delete_city_rbi_log_data_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sebi_log',
            fields=[
                ('Sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=255)),
                ('script_status', models.CharField(max_length=255)),
                ('data_available', models.IntegerField(default=0)),
                ('data_scraped', models.IntegerField(default=0)),
                ('total_record_count', models.IntegerField(default=0)),
                ('month', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('failure_reason', models.CharField(max_length=255)),
                ('comments', models.CharField(max_length=255)),
                ('data_updated', models.IntegerField(default=0)),
                ('source_status', models.CharField(default='Active', max_length=255)),
                ('date_of_scraping', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sebi_log',
            },
        ),
        migrations.AddField(
            model_name='rbi_log',
            name='source_status',
            field=models.CharField(default='Active', max_length=255),
        ),
        migrations.AlterField(
            model_name='rbi_log',
            name='Sr_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rbi_log',
            name='data_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rbi_log',
            name='data_scraped',
            field=models.IntegerField(default=0),
        ),
    ]
