# Generated by Django 4.2.9 on 2024-02-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probe_agile_data', '0008_sebi_log_rbi_log_source_status_alter_rbi_log_sr_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mca_log',
            fields=[
                ('Sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=255)),
                ('script_status', models.CharField(max_length=255)),
                ('data_available', models.IntegerField(default=0)),
                ('data_scraped', models.IntegerField(default=0)),
                ('total_record_count', models.IntegerField(default=0)),
                ('failure_reason', models.CharField(max_length=255)),
                ('comments', models.CharField(max_length=255)),
                ('source_status', models.CharField(default='Active', max_length=255)),
                ('date_of_scraping', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mca_log',
            },
        ),
        migrations.RemoveField(
            model_name='sebi_log',
            name='data_updated',
        ),
        migrations.RemoveField(
            model_name='sebi_log',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='sebi_log',
            name='month',
        ),
        migrations.RemoveField(
            model_name='sebi_log',
            name='year',
        ),
    ]
