# Generated by Django 4.2.9 on 2024-04-29 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('probe_agile_data', '0011_pfrda_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='irdai_log',
        ),
        migrations.DeleteModel(
            name='mca_log',
        ),
        migrations.DeleteModel(
            name='rbi_log',
        ),
        migrations.DeleteModel(
            name='sebi_log',
        ),
    ]
