# Generated by Django 4.2.7 on 2024-02-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0003_scraping_log_total_record_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraping_log',
            name='source_status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterModelTable(
            name='scraping_log',
            table='scraping_log_bse_nse',
        ),
    ]
