# Generated by Django 4.2.7 on 2024-02-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0004_scraping_log_source_status_alter_scraping_log_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scraping_log',
            table='scraping_log1',
        ),
    ]
