# Generated by Django 4.2.9 on 2024-02-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0006_alter_scraping_log_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scraping_log',
            table='scraping_log_bse_nse',
        ),
    ]
