"""
Django settings for dashboardmarketdata project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import configparser

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read the SECRET_KEY value from secretkey.ini
# config = configparser.ConfigParser()
# config.read(os.path.join(BASE_DIR, 'config', 'secretkey.ini'))
# SECRET_KEY = config['secret_key']['key']

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2o7i-xpc1jz_6)c^-(s$_b0k$8wm*ynh_mw*$ag2w^1+gl30@e'



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'market_data',
    'probe_agile_data'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'probe_agile_dashboard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'probe_agile_dashboard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases




DATABASES = {
    'default': {
        'NAME': 'bse',
        'ENGINE': 'django.db.backends.mysql'  ,   # 'django.db.backends.mysql'  'mysql.connector.django'
        'USER': 'root1',
        'PASSWORD': 'Mysql1234$',
        'HOST': '4.213.77.165',
        'PORT': 3306,
        'OPTIONS': {
            'autocommit': True,
        },
    },
    'rbi': {
        'NAME': 'rbi',
        'ENGINE': 'django.db.backends.mysql'  ,   # 'django.db.backends.mysql'  'mysql.connector.django'
        'USER': 'root1',
        'PASSWORD': 'Mysql1234$',
        'HOST': '4.213.77.165',
        'PORT': 3306,
        'OPTIONS': {
            'autocommit': True,
        },
    },
    'sebi': {
        'NAME': 'sebi',
        'ENGINE': 'django.db.backends.mysql'  ,   # 'django.db.backends.mysql'  'mysql.connector.django'
        'USER': 'root1',
        'PASSWORD': 'Mysql1234$',
        'HOST': '4.213.77.165',
        'PORT': 3306,
        'OPTIONS': {
            'autocommit': True,
        },
    },
     'mca': {
        'NAME': 'mca',
        'ENGINE':'django.db.backends.mysql' ,   # 'django.db.backends.mysql'  'mysql.connector.django'
        'USER': 'root1',
        'PASSWORD': 'Mysql1234$',
        'HOST': '4.213.77.165',
        'PORT': 3306,
        'OPTIONS': {
            'autocommit': True,
        },
    },
     'irdai': {
        'NAME': 'irdai',
        'ENGINE': 'django.db.backends.mysql'  ,   # 'django.db.backends.mysql'  'mysql.connector.django'
        'USER': 'root1',
        'PASSWORD': 'Mysql1234$',
        'HOST': '4.213.77.165',
        'PORT': 3306,
        'OPTIONS': {
            'autocommit': True,
        },
    },
     'pfrda': {
        'NAME': 'pfrda',
        'ENGINE': 'django.db.backends.mysql'  ,   # 'django.db.backends.mysql'  'mysql.connector.django'
        'USER': 'root1',
        'PASSWORD': 'Mysql1234$',
        'HOST': '4.213.77.165',
        'PORT': 3306,
        'OPTIONS': {
            'autocommit': True,
        },
    },
    'cci': {
        'NAME': 'cci',
        'ENGINE': 'django.db.backends.mysql'  ,   # 'django.db.backends.mysql'  'mysql.connector.django'
        'USER': 'root1',
        'PASSWORD': 'Mysql1234$',
        'HOST': '4.213.77.165',
        'PORT': 3306,
        'OPTIONS': {
            'autocommit': True,
        },
    },
    'nsdl': {
        'NAME': 'nsdl',
        'ENGINE': 'django.db.backends.mysql'  ,   # 'django.db.backends.mysql'  'mysql.connector.django'
        'USER': 'root1',
        'PASSWORD': 'Mysql1234$',
        'HOST': '4.213.77.165',
        'PORT': 3306,
        'OPTIONS': {
            'autocommit': True,
        },
    },
    'gem': {
        'NAME': 'gem',
        'ENGINE': 'django.db.backends.mysql'  ,   # 'django.db.backends.mysql'  'mysql.connector.django'
        'USER': 'root1',
        'PASSWORD': 'Mysql1234$',
        'HOST': '4.213.77.165',
        'PORT': 3306,
        'OPTIONS': {
            'autocommit': True,
        },
    },
    'startup_india': {
        'NAME': 'startup_india',
        'ENGINE': 'django.db.backends.mysql'  ,   # 'django.db.backends.mysql'  'mysql.connector.django'
        'USER': 'root1',
        'PASSWORD': 'Mysql1234$',
        'HOST': '4.213.77.165',
        'PORT': 3306,
        'OPTIONS': {
            'autocommit': True,
        },
    },
    'ngo': {
        'NAME': 'ngo',
        'ENGINE': 'django.db.backends.mysql'  ,   # 'django.db.backends.mysql'  'mysql.connector.django'
        'USER': 'root1',
        'PASSWORD': 'Mysql1234$',
        'HOST': '4.213.77.165',
        'PORT': 3306,
        'OPTIONS': {
            'autocommit': True,
        },
    },
}

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Example using Redis as the message broker
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
